### ISSUE TITLE
Banner: Incorrect margin from the navigation button to the end of the banner section.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#116]
![image](https://cloud.githubusercontent.com/assets/18568310/17579080/bc144a3e-5fc3-11e6-8123-f965e1efc34d.png)

**Comment by titandigitalbkk** [comment]
fixed

**Comment by ricatitan** [comment]
Error still the same
![image](https://cloud.githubusercontent.com/assets/18568310/17845972/52afd71c-6878-11e6-812b-3a42a660b757.png)
